"""``--emit``: the commands that carry out the plan."""

from __future__ import annotations

import json

import pytest

from django_upgrade_report import cli, commands
from django_upgrade_report.analysis import PackageReport, Phase, Report, Status


@pytest.fixture
def plan_project(project):
    (project / "requirements.txt").write_text(
        "Django==4.2.7\ndjango-ready==1.0\ndjango-before==1.0\ndjango-with==2.0\n"
        "django-blocked==1.0\ndjango-lagging==1.0\n"
    )
    return project


def emit(project, capsys, *args):
    assert cli.main([str(project), "--emit", *args]) == 0
    return capsys.readouterr().out


def test_uv(plan_project, capsys):
    assert emit(plan_project, capsys, "uv") == (
        "# Django 4.2.7 → 5.2, generated by django-upgrade-report "
        f"{cli.__version__}\n"
        "# 1. Upgrade first: one at a time, run your tests after each\n"
        "uv add 'django-before>=2.0'\n"
        "# 2. Together with Django: one change\n"
        "uv add 'django>=5.2,<5.3' 'django-with>=3.0'\n"
        "# Not included, they need a person: django-blocked (blocked), django-lagging (check)\n"
    )


@pytest.mark.parametrize(
    ("tool", "first", "together"),
    [
        (
            "poetry",
            "poetry add 'django-before@>=2.0'",
            "poetry add 'django@~5.2' 'django-with@>=3.0'",
        ),
        ("pdm", "pdm add 'django-before>=2.0'", "pdm add 'django~=5.2.0' 'django-with>=3.0'"),
        (
            "pipenv",
            "pipenv install 'django-before>=2.0'",
            "pipenv install 'django~=5.2.0' 'django-with>=3.0'",
        ),
    ],
)
def test_other_tools(plan_project, capsys, tool, first, together):
    lines = emit(plan_project, capsys, tool).splitlines()
    assert lines[2:5] == [first, "# 2. Together with Django: one change", together]


def test_pip_says_which_lines_to_change(plan_project, capsys):
    lines = emit(plan_project, capsys, "pip").splitlines()
    assert lines[2:6] == [
        "# requirements.txt:3  django-before==1.0  →  django-before==2.0",
        "# 2. Together with Django: one change",
        "# requirements.txt:1  Django==4.2.7  →  Django~=5.2.0",
        "# requirements.txt:4  django-with==2.0  →  django-with==3.0",
    ]


def test_pip_points_at_the_pin_in_an_included_file(plan_project, capsys):
    base = plan_project / "requirements" / "base.txt"
    base.parent.mkdir()
    base.write_text("# shared\nDjango==4.2.7\n\ndjango-before \\\n    ==1.0\n")
    (plan_project / "constraints.txt").write_text("django-with==2.0\n")
    (plan_project / "requirements.txt").write_text(
        "-r requirements/base.txt\n-c constraints.txt\ndjango-with\n"
    )
    lines = emit(plan_project, capsys, "pip").splitlines()
    assert "# requirements/base.txt:4  django-before==1.0  →  django-before==2.0" in lines
    assert "# requirements/base.txt:2  Django==4.2.7  →  Django~=5.2.0" in lines
    assert "# constraints.txt:1  django-with==2.0  →  django-with==3.0" in lines  # the pin


def test_python_comes_first(plan_project, index, capsys):
    (plan_project / ".python-version").write_text("3.10\n")
    for r in index.packages["django-before"][:3]:
        r["requires_python"] = "<3.12"
    out = emit(plan_project, capsys, "uv", "--python-target", "3.12")
    lines = out.splitlines()
    assert lines[1] == "# 0. Python 3.12 first: upgrade these, then switch to Python 3.12"
    assert lines[2].startswith("# No Django 4.2 release declares Python 3.12")  # django_note
    assert lines[3] == "uv add 'django-before>=2.1'"
    assert lines[4] == "# 1. Upgrade first: one at a time, run your tests after each"


def test_auto_follows_the_source(plan_project, capsys):
    assert "→  django-before==2.0" in emit(plan_project, capsys, "auto")  # requirements: pip
    (plan_project / "pyproject.toml").write_text(
        '[project]\ndependencies = ["Django==4.2.7", "django-before==1.0"]\n'
    )
    assert "→  django-before==2.0" in emit(plan_project, capsys, "auto")  # both: still pip
    (plan_project / "requirements.txt").unlink()
    assert cli.main([str(plan_project), "--emit", "auto"]) == 2
    assert "--emit auto cannot tell the tool from pyproject.toml" in capsys.readouterr().err


def test_transitive_packages_are_upgraded_in_the_lock(plan_project, capsys):
    (plan_project / "requirements.txt").unlink()
    packages = "".join(
        f'\n[[package]]\nname = "{name}"\nversion = "{version}"\n'
        'source = { registry = "https://pypi.org/simple" }\n'
        for name, version in (("django", "4.2.7"), ("django-before", "1.0"), ("django-with", "2.0"))
    )
    (plan_project / "uv.lock").write_text(
        'version = 1\n\n[[package]]\nname = "app"\nversion = "0.1.0"\n'
        'source = { virtual = "." }\n'
        'dependencies = [{ name = "django" }, { name = "django-with" }]\n' + packages
    )
    lines = emit(plan_project, capsys, "auto").splitlines()
    assert lines[2] == "uv lock --upgrade-package django-before==2.0"  # nothing to quote
    assert lines[4] == "uv add 'django>=5.2,<5.3' 'django-with>=3.0'"
    lines = emit(plan_project, capsys, "poetry").splitlines()
    assert lines[2] == "poetry update django-before  # comes with another package: to 2.0"


def row(name, phase, notes=(), direct=True):
    return PackageReport(
        name=name,
        display_name=name,
        current="1.0",
        spec="",
        latest="2.0",
        status=Status.UPGRADE,
        reason="",
        target_version="2.0",
        phase=phase,
        notes=list(notes),
        direct=direct,
    )


def test_upgrades_that_need_each_other_go_in_one_command():
    report = Report(
        target="5.2",
        current_django="4.2.7",
        django_requires_python=None,
        source="uv.lock",
        packages=[
            row("a", Phase.BEFORE, ["upgrade together with c"]),
            row("b", Phase.BEFORE),
            row("c", Phase.BEFORE, ["upgrade together with a"]),
        ],
        skipped=0,
        missing=[],
    )
    steps = commands.plan(report, "uv").steps
    assert steps[0].commands == ["uv add 'a>=2.0' 'c>=2.0'", "uv add 'b>=2.0'"]


def test_a_health_check_has_no_django_step():
    report = Report(
        target="5.2",
        current_django="5.2.1",
        django_requires_python=None,
        source="uv.lock",
        packages=[row("a", None)],
        skipped=0,
        missing=[],
    )
    steps = commands.plan(report, "uv").steps
    assert [(s.phase, s.commands) for s in steps] == [("upgrade", ["uv add 'a>=2.0'"])]


def test_json_carries_the_commands(plan_project, capsys):
    cli.main([str(plan_project), "-f", "json"])
    assert json.loads(capsys.readouterr().out)["commands"] is None
    cli.main([str(plan_project), "-f", "json", "--emit", "uv"])
    emitted = json.loads(capsys.readouterr().out)["commands"]
    assert emitted["tool"] == "uv"
    assert emitted["steps"][1] == {
        "phase": "with",
        "commands": ["uv add 'django>=5.2,<5.3' 'django-with>=3.0'"],
    }
    assert emitted["left_out"] == ["django-blocked (blocked)", "django-lagging (check)"]


def test_html_rows_show_their_command(plan_project, capsys):
    (plan_project / "requirements.txt").unlink()
    (plan_project / "Pipfile.lock").write_text(
        json.dumps(
            {"default": {"django": {"version": "==4.2.7"}, "django-before": {"version": "==1.0"}}}
        )
    )
    cli.main([str(plan_project), "-f", "html"])
    page = capsys.readouterr().out
    assert (
        "<dt>Command</dt><dd><code>pipenv install &#x27;django-before&gt;=2.0&#x27;</code>" in page
    )


@pytest.mark.parametrize(
    ("args", "message"),
    [
        (["-f", "markdown"], "not --format markdown"),
        (["-f", "html"], "not --format html"),
        (["-q"], "not --quiet"),
    ],
)
def test_emit_goes_with_text_or_json(plan_project, capsys, args, message):
    assert cli.main([str(plan_project), "--emit", "uv", *args]) == 2
    assert message in capsys.readouterr().err
