"""Markdown for pull request comments and ``$GITHUB_STEP_SUMMARY``."""

from __future__ import annotations

from django_upgrade_report.analysis import Report
from django_upgrade_report.render import headline, sections, summary, version_cell

_ICON = {
    "blocked": "⛔",
    "before": "⬆️",
    "with": "⬆️",
    "upgrade": "⬆️",
    "check": "❔",
    "ready": "✅",
}


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def render(report: Report) -> str:
    lines = [
        f"## {headline(report)}",
        "",
        f"**{summary(report)}** · from `{report.source}`",
        "",
    ]
    for section in sections(report):
        lines.append(f"### {_ICON[section.key]} {section.title} ({len(section.packages)})")
        lines.append("")
        if section.key == "ready":
            lines.append(", ".join(f"`{p.display_name}`" for p in section.packages))
            lines.append("")
            continue
        lines.append(section.hint)
        lines.append("")
        lines.append("| Package | Version | Why |")
        lines.append("| --- | --- | --- |")
        for p in section.packages:
            why = "; ".join([p.reason, *p.notes])
            lines.append(f"| `{p.display_name}` | {_cell(version_cell(p))} | {_cell(why)} |")
        lines.append("")
    if report.django_requires_python:
        lines.append(f"Django {report.target} requires Python `{report.django_requires_python}`.")
        lines.append("")
    lines.append(
        "<sub>Generated by [django-upgrade-report](https://github.com/derblub/django-upgrade-report)"
        "</sub>"
    )
    return "\n".join(lines) + "\n"
