"""Markdown for pull request comments and ``$GITHUB_STEP_SUMMARY``."""

from __future__ import annotations

import re

from django_upgrade_report import AUTHOR, COMPANY, COMPANY_URL, REPO_URL
from django_upgrade_report.analysis import PackageReport, Report
from django_upgrade_report.render import (
    change_rows,
    changes_title,
    headline,
    private_index_hint,
    python_hint,
    python_line,
    python_summary,
    row_links,
    row_notes,
    sections,
    skipped_line,
    split_noted,
    summary,
    version_cell,
)

_ICON = {
    "blocked": "⛔",
    "before": "⬆️",
    "with": "⬆️",
    "upgrade": "⬆️",
    "check": "❔",
    "ready": "✅",
}

# Inline markup characters. Block markup (``#``, ``-``, ...) only counts at the start of a
# line, and no escaped text starts a line.
_MARKUP = re.compile(r"([\\`*_\[\]<>|~&])")


def escape(text: str) -> str:
    """``text`` shown literally, e.g. ``!=4.0.*,!=4.1.*`` without turning into emphasis."""
    return _MARKUP.sub(r"\\\1", text)


def _cell(text: str) -> str:
    return "<br>".join(escape(line) for line in text.splitlines() or [""])


def _code(text: str) -> str:
    """An inline code span that survives backticks inside ``text``."""
    longest = max((len(run) for run in re.findall(r"`+", text)), default=0)
    fence = "`" * (longest + 1)
    pad = " " if text.startswith("`") or text.endswith("`") else ""
    return f"{fence}{pad}{text}{pad}{fence}"


def _table(packages: list[PackageReport]) -> list[str]:
    lines = ["| Package | Version | Why |", "| --- | --- | --- |"]
    for p in packages:
        why = _cell("; ".join([p.reason, *row_notes(p)]))
        why += "".join(f" · [{label}]({url})" for label, url in row_links(p))
        lines.append(f"| {_code(p.display_name)} | {_cell(version_cell(p))} | {why} |")
    return lines


def _changes(report: Report) -> list[str]:
    rows = change_rows(report)
    if not rows:
        return [f"_{escape(changes_title(report))}._", ""]
    lines = [f"### {escape(changes_title(report))}", "", "| | Package | Change | Why |"]
    lines.append("| --- | --- | --- | --- |")
    for _, mark, name, step, why in rows:
        package = _code(name) if name else ""
        lines.append(f"| {mark} | {package} | {_cell(step)} | {_cell(why)} |")
    return [*lines, ""]


def render(report: Report, only_changes: bool = False) -> str:
    lines = [
        f"## {escape(headline(report))}",
        "",
        f"**{summary(report)}** · from {_code(report.source)}",
        "",
    ]
    if report.notices:
        lines += [" ".join(f"{escape(n)}." for n in report.notices), ""]
    if report.warnings:
        lines.append("> [!WARNING]")
        lines += [f"> {escape(w)}  " for w in report.warnings]
        lines.append("")
    if report.changes is not None:
        lines += _changes(report)
        if only_changes:
            return "\n".join(lines).rstrip() + "\n"
    plan = report.python
    if plan is not None:
        if plan.packages:
            lines += [f"### 🐍 Python {plan.target} first ({len(plan.packages)})", ""]
            lines += [escape(python_hint(report)), "", *_table(plan.packages), ""]
        else:
            lines += [f"### 🐍 Python {plan.target}", ""]
        lines += [f"{escape(line)}.  " for line in python_summary(report)]
        lines.append("")
    for section in sections(report):
        lines.append(f"### {_ICON[section.key]} {section.title} ({len(section.packages)})")
        lines.append("")
        if section.key == "ready":
            plain, noted = split_noted(section.packages)
            if plain:
                lines += [", ".join(_code(p.display_name) for p in plain), ""]
            if noted:
                lines += [*_table(noted), ""]
            continue
        lines += [escape(section.hint), ""]
        lines += [*_table(section.packages), ""]

    if report.missing:
        missing = ", ".join(_code(m) for m in report.missing)
        lines += [f"**Not on the package index:** {missing}", ""]
    if report.external:
        lines.append("**Not from PyPI, not checked:**")
        lines.append("")
        lines += [f"- {_code(name)}: {_code(where)}" for name, where in report.external]
        lines.append("")
        hint = private_index_hint(report)
        if hint:
            lines += [f"{escape(hint)}.", ""]
    if report.skipped:
        lines += [f"{skipped_line(report)}.", ""]
    python = python_line(report)
    if python:
        lines += [f"{escape(python)}.", ""]
    lines.append(
        f"<sub>Generated by [django-upgrade-report]({REPO_URL}) "
        f"by {AUTHOR}, [{COMPANY}]({COMPANY_URL})</sub>"
    )
    return "\n".join(lines) + "\n"
