"""Write the wiki pages that are generated from the code, or check that they are up to date.

    PYTHONPATH=src python3 scripts/wiki.py           # rewrite them
    PYTHONPATH=src python3 scripts/wiki.py --check   # exit 1 when one is out of date

The other pages in docs/wiki/ are written by hand. A workflow publishes the folder to the
GitHub wiki on every push to main.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from django_upgrade_report import cli
from django_upgrade_report.render import json as json_report

WIKI = Path(__file__).resolve().parent.parent / "docs" / "wiki"
NOTICE = "<!-- Generated by scripts/wiki.py from the code. Edit the code, then run it. -->"


def command_line() -> str:
    parser = cli.build_parser()
    lines = [
        NOTICE,
        "# Command-line reference",
        "",
        "```console",
        "django-upgrade-report [PROJECT] [options]",
        "```",
        "",
        "Every option, as `django-upgrade-report --help` describes it. The pages "
        "[Getting started](Getting-Started), [How it decides](How-It-Decides) and "
        "[Continuous integration](Continuous-Integration) show them at work.",
        "",
        "| Option | Value | Default | What it does |",
        "| --- | --- | --- | --- |",
    ]
    for action in parser._actions:
        if isinstance(action, argparse._HelpAction):
            continue
        names = (
            ", ".join(f"`{name}`" for name in action.option_strings) or f"`{action.dest.upper()}`"
        )
        if action.choices:
            value = " ".join(f"`{choice}`" for choice in action.choices)
        elif action.nargs == 0:
            value = ""
        else:
            value = f"`{action.metavar or action.dest.upper()}`"
        default = action.default
        shown = "" if default in (None, False, [], argparse.SUPPRESS) else f"`{default}`"
        text = " ".join((action.help or "").split()).replace("%(prog)s", "django-upgrade-report")
        text = text.replace("|", "\\|")
        lines.append(f"| {names} | {value} | {shown} | {text[:1].upper()}{text[1:]}. |")
    lines += [
        "",
        "## Exit status",
        "",
        "| Status | Meaning |",
        "| --- | --- |",
        "| `0` | The report was written, and nothing matched `--fail-on`, `--fail-on-python` or "
        "`--fail-on-change`. |",
        "| `1` | Something matched one of them. |",
        "| `2` | The report could not be made: no dependencies found, an unreadable file, an "
        "unknown target, the index could not be reached, or with `--fail-on` a report that "
        "is incomplete. With `--errors-as-warnings` these exit with `0` and print a "
        "warning. |",
        "",
    ]
    return "\n".join(lines)


def json_reference() -> str:
    doc = json_report.__doc__ or ""
    _, _, fields = doc.partition("Top level (schema_version 1):")
    # The docstring is reStructuredText: ``code`` becomes `code`.
    fields = re.sub(r"``([^`]+)``", r"`\1`", fields.strip())
    lines = [
        NOTICE,
        "# JSON report reference",
        "",
        "`django-upgrade-report --format json` writes one JSON document. Its shape is "
        f"versioned by `schema_version`, now `{json_report.SCHEMA_VERSION}`: adding a field "
        "keeps the version, renaming, removing or retyping one bumps it. Read `kind` before "
        "anything else.",
        "",
        "## Fields",
        "",
        fields,
        "",
        "## Reading it",
        "",
        "```console",
        "django-upgrade-report --format json -o report.json",
        "jq -r '.packages[] | select(.status == \"blocked\") | .name' report.json",
        "jq '.counts' report.json",
        "```",
        "",
    ]
    return "\n".join(lines)


ACTION = Path(__file__).resolve().parent.parent / "action.yml"


def _action_fields(section: str) -> list[tuple[str, str, str]]:
    """(name, description, default) of the action's inputs or outputs.

    A small reader for the shape action.yml has, so the script needs nothing but the package.
    """
    fields: list[tuple[str, str, str]] = []
    inside = False
    for line in ACTION.read_text(encoding="utf-8").splitlines():
        if not line.startswith(" "):
            inside = line == f"{section}:"
            continue
        if not inside:
            continue
        if re.match(r"^  [a-z-]+:$", line):
            fields.append((line.strip()[:-1], "", ""))
        elif match := re.match(r"^    (description|default): ?(.*)$", line):
            key, value = match.groups()
            value = value.strip()
            if len(value) > 1 and value[0] == value[-1] and value[0] in "\"'":
                value = value[1:-1]
            name, description, default = fields[-1]
            if key == "description":
                description = value
            else:
                default = value
            fields[-1] = (name, description, default)
    return fields


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def action_reference() -> str:
    lines = [
        NOTICE,
        "# GitHub Action reference",
        "",
        "```yaml",
        "- uses: actions/checkout@v7",
        "- uses: derblub/django-upgrade-report@v0",
        "  id: django",
        "  with:",
        "    fail-on: blocked",
        "```",
        "",
        "Every input and output of the action, as `action.yml` describes them. "
        "[Continuous integration](Continuous-Integration) shows them in whole workflows.",
        "",
        "## Inputs",
        "",
        "| Input | Default | What it does |",
        "| --- | --- | --- |",
    ]
    for name, description, default in _action_fields("inputs"):
        shown = f"`{default}`" if default else ""
        lines.append(f"| `{name}` | {shown} | {_cell(description)} |")
    lines += ["", "## Outputs", "", "| Output | What it holds |", "| --- | --- |"]
    for name, description, _ in _action_fields("outputs"):
        lines.append(f"| `{name}` | {_cell(description)} |")
    lines += [
        "",
        "The action brings its own Python, runs on Linux and Windows runners, caches answers "
        "from PyPI between runs, and writes the Markdown report to the job summary. The summary "
        "and the outputs are written before `fail-on` fails the step.",
        "",
    ]
    return "\n".join(lines)


PAGES = {
    "Command-Line-Reference.md": command_line,
    "JSON-Report-Reference.md": json_reference,
    "GitHub-Action-Reference.md": action_reference,
}


def main(argv: list[str]) -> int:
    stale = []
    for name, build in PAGES.items():
        path = WIKI / name
        text = build()
        if "--check" in argv:
            if not path.is_file() or path.read_text(encoding="utf-8") != text:
                stale.append(name)
        else:
            path.write_text(text, encoding="utf-8", newline="\n")
    if stale:
        print(f"out of date: {', '.join(stale)}; run scripts/wiki.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
