"""``--emit``: the commands that carry out the plan, for the tool that manages the project.

The steps follow the report: what to upgrade first, one at a time and in the report's order,
then Django together with what needs it, in one change. Packages to check or blocked, and
packages not from PyPI, are named but left out: they need a person.
"""

from __future__ import annotations

import json
import re
import shlex
from dataclasses import dataclass, field
from pathlib import PurePath

from django_upgrade_report import __version__
from django_upgrade_report.analysis import PackageReport, Phase, Report, Status
from django_upgrade_report.render import headline

TOOLS = ("uv", "poetry", "pdm", "pip", "pipenv")
_BY_SOURCE = {
    "uv.lock": "uv",
    "poetry.lock": "poetry",
    "pdm.lock": "pdm",
    "Pipfile.lock": "pipenv",
}


class EmitError(ValueError):
    """No tool can be told from the report's source."""


@dataclass
class Step:
    phase: str
    """``"python"`` (before switching Python), ``"before"``, ``"with"`` or ``"upgrade"``
    (an upgrade without a phase)."""
    title: str
    commands: list[str] = field(default_factory=list)


@dataclass
class Commands:
    tool: str
    steps: list[Step]
    left_out: list[str]
    """Packages not included, with why: ``"django-taggit (blocked)"``."""


def tool_for(report: Report, wanted: str) -> str:
    """``wanted``, or for ``auto`` the tool the report's source belongs to."""
    if wanted != "auto":
        return wanted
    names = [PurePath(part.strip()).name for part in report.source.split(",")]
    for name in names:
        if name in _BY_SOURCE:
            return _BY_SOURCE[name]
    if any(n.startswith("requirements") or n.endswith((".txt", ".in")) for n in names):
        return "pip"  # with a pyproject.toml beside them, pip installs that too
    if report.source.startswith("packages installed for "):
        return "pip"
    raise EmitError(
        f"--emit auto cannot tell the tool from {report.source}: name it, one of {', '.join(TOOLS)}"
    )


def plan(report: Report, tool: str) -> Commands:
    """The steps for ``tool`` (one of :data:`TOOLS`)."""
    left_out = [
        f"{p.display_name} ({p.status.value})"
        for p in report.packages
        if p.status in (Status.BLOCKED, Status.CHECK)
    ]
    left_out += [
        f"{p.display_name} (not from PyPI)" for p in report.by_status(Status.UPGRADE) if p.source
    ]
    upgrades = [p for p in report.by_status(Status.UPGRADE) if not p.source]
    steps = []
    python = report.python
    if python is not None and (python.packages or python.django_note):
        step = Step(
            "python",
            f"Python {python.target} first: upgrade these, then switch to Python {python.target}",
        )
        if python.django_note:  # e.g. a newer Django patch release first
            step.commands.append(f"# {python.django_note}")
        for group in _groups([p for p in python.packages if p.status is Status.UPGRADE]):
            step.commands += _install(tool, group)
        steps.append(step)
        left_out += [
            f"{p.display_name} ({p.status.value} on Python {python.target})"
            for p in python.packages
            if p.status in (Status.BLOCKED, Status.CHECK)
        ]
    before = [p for p in upgrades if p.phase is Phase.BEFORE]
    if before:
        step = Step("before", "Upgrade first: one at a time, run your tests after each")
        for group in _groups(before):
            step.commands += _install(tool, group)
        steps.append(step)
    together = [p for p in upgrades if p.phase is Phase.WITH]
    if not report.health_check:
        step = Step("with", "Together with Django: one change")
        django = (report.current_django, report.target, report.django_origin)
        step.commands += _install(tool, together, django=django)
        steps.append(step)
    loose = [p for p in upgrades if p.phase is None]
    if loose:
        step = Step("upgrade", "Upgrade: one at a time, run your tests after each")
        for group in _groups(loose):
            step.commands += _install(tool, group)
        steps.append(step)
    return Commands(tool, steps, left_out)


def command(report: Report, p: PackageReport, tool: str) -> str | None:
    """The command for one package on its own, ``None`` when it has none."""
    if p.status is not Status.UPGRADE or p.source or not p.target_version:
        return None
    lines = _install(tool, [p])
    return lines[0] if len(lines) == 1 else None


def render(report: Report, commands: Commands) -> str:
    lines = [f"# {headline(report)}, generated by django-upgrade-report {__version__}"]
    first = 0 if commands.steps and commands.steps[0].phase == "python" else 1
    for number, step in enumerate(commands.steps, first):
        lines.append(f"# {number}. {step.title}")
        lines += step.commands or ["# nothing to do"]
    if commands.left_out:
        lines.append(f"# Not included, they need a person: {', '.join(commands.left_out)}")
    return "\n".join(lines) + "\n"


def as_dict(commands: Commands) -> dict:
    return {
        "tool": commands.tool,
        "steps": [{"phase": s.phase, "commands": s.commands} for s in commands.steps],
        "left_out": commands.left_out,
    }


def _groups(packages: list[PackageReport]) -> list[list[PackageReport]]:
    """One group per package, in order, except upgrades that need each other: one group."""
    by_display = {p.display_name: p for p in packages}
    placed: set[str] = set()
    groups = []
    for p in packages:
        if p.name in placed:
            continue
        group = [p]
        for note in p.notes:
            if note.startswith("upgrade together with "):
                names = note.removeprefix("upgrade together with ").split(", ")
                group += [by_display[n] for n in names if n in by_display]
        placed.update(q.name for q in group)
        groups.append(group)
    return groups


def _install(
    tool: str,
    packages: list[PackageReport],
    django: tuple[str | None, str, str | None] | None = None,
) -> list[str]:
    """The lines that move ``packages`` up together, and Django from ``django[0]`` (the
    current version, if known) to ``django[1]`` (X.Y); ``django[2]`` is where it is pinned."""
    direct = [p for p in packages if p.direct is not False]
    transitive = [p for p in packages if p.direct is False]
    q = shlex.quote
    if tool == "pip":
        lines = [
            _change(
                p.origin, _pin(p.display_name, p.current), f"{p.display_name}=={p.target_version}"
            )
            for p in direct
        ]
        if django:
            lines.insert(0, _change(django[2], _pin("Django", django[0]), f"Django~={django[1]}.0"))
        lines += [
            f"# in a constraints file: {p.display_name}=={p.target_version}" for p in transitive
        ]
        return lines
    specs = [_spec(tool, p) for p in direct]
    if django:
        specs.insert(0, _django(tool, django[1]))
    lines = []
    if specs:
        add = {"uv": "uv add", "poetry": "poetry add", "pdm": "pdm add", "pipenv": "pipenv install"}
        lines.append(f"{add[tool]} {' '.join(q(s) for s in specs)}")
    for p in transitive:
        if tool == "uv":
            lines.append(f"uv lock --upgrade-package {q(f'{p.name}=={p.target_version}')}")
        else:
            update = "pipenv update" if tool == "pipenv" else f"{tool} update"
            lines.append(
                f"{update} {q(p.name)}  # comes with another package: to {p.target_version}"
            )
    return lines


def _change(origin: str | None, old: str, new: str) -> str:
    """A requirement line to change, with the file and line it is on when known."""
    return f"# {origin + '  ' if origin else ''}{old}  →  {new}"


def _pin(name: str, version: str | None) -> str:
    return f"{name}=={version}" if version else name


def _spec(tool: str, p: PackageReport) -> str:
    if tool == "poetry":
        return f"{p.name}@>={p.target_version}"
    return f"{p.name}>={p.target_version}"


def _django(tool: str, target: str) -> str:
    major, _, minor = target.partition(".")
    if tool == "uv":
        return f"django>={target},<{major}.{int(minor) + 1}"
    if tool == "poetry":
        return f"django@~{target}"
    return f"django~={target}.0"


# --- configuration for the pull request bots ------------------------------------------

BOTS = ("renovate", "dependabot")


def renovate(report: Report) -> str:
    """``packageRules`` for Renovate that follow the plan, as JSON."""
    rules = []
    hold = _hold(report)
    if hold:
        rules.append(
            {
                "description": f"django-upgrade-report: hold Django at {hold[0]} until the "
                "'upgrade first' list is done, then remove this rule",
                "matchPackageNames": ["django"],
                "allowedVersions": f"<{hold[1]}",
            }
        )
    for names, title, why in _bot_groups(report):
        rules.append(
            {
                "description": f"django-upgrade-report: {why}",
                "matchPackageNames": names,
                "groupName": title,
            }
        )
    first = [p.name for p in _upgrades(report) if p.phase is Phase.BEFORE]
    if first:
        rules.append(
            {
                "description": "django-upgrade-report: upgrade first, one at a time",
                "matchPackageNames": first,
                "minimumReleaseAge": "0 days",
            }
        )
    return json.dumps({"packageRules": rules}, indent=2) + "\n"


def dependabot(report: Report) -> str:
    """Keys for the pip entry of ``.github/dependabot.yml`` that follow the plan."""
    lines = [
        f"# {headline(report)}, generated by django-upgrade-report {__version__}",
        "# Add these keys to the entry for your Python dependencies under updates:",
    ]
    groups = _bot_groups(report)
    if groups:
        lines.append("    groups:")
        for names, title, _ in groups:
            lines.append(f"      {_slug(title)}:")
            lines.append("        patterns:")
            lines += [f'          - "{name}"' for name in names]
    hold = _hold(report)
    if hold:
        lines += [
            "    ignore:",
            f"      # Hold Django at {hold[0]} until the 'upgrade first' list is done, "
            "then remove this.",
            '      - dependency-name: "django"',
            f'        versions: [">={hold[1]}"]',
        ]
    if not groups and not hold:
        lines.append("# Nothing to add: the plan needs no group and no hold.")
    return "\n".join(lines) + "\n"


def _upgrades(report: Report) -> list[PackageReport]:
    return [p for p in report.by_status(Status.UPGRADE) if not p.source]


def _hold(report: Report) -> tuple[str, str] | None:
    """(the Django series to stay on, the next one) while there is something to upgrade first."""
    if report.health_check or not report.current_django:
        return None
    if not any(p.phase is Phase.BEFORE for p in _upgrades(report)):
        return None
    try:
        major, minor = (int(part) for part in report.current_django.split(".")[:2])
    except ValueError:
        return None
    following = f"{major + 1}.0" if minor >= 2 else f"{major}.{minor + 1}"  # 4.2 is followed by 5.0
    return f"{major}.{minor}", following


def _bot_groups(report: Report) -> list[tuple[list[str], str, str]]:
    """(names, group name, why) for packages a bot should upgrade in one pull request:
    Django with what needs it, and upgrades that need each other."""
    groups = []
    upgrades = _upgrades(report)
    together = [p.name for p in upgrades if p.phase is Phase.WITH]
    if together and not report.health_check:
        why = f"these go together with Django {report.target}"
        groups.append((["django", *together], f"Django {report.target}", why))
    for group in _groups([p for p in upgrades if p.phase is not Phase.WITH]):
        if len(group) > 1:
            names = [p.name for p in group]
            title = f"{' and '.join(names)} together"
            groups.append((names, title, f"{title}: each needs the other"))
    return groups


def _slug(title: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
