"""``--emit``: the commands that carry out the plan, for the tool that manages the project.

The steps follow the report: what to upgrade first, one at a time and in the report's order,
then Django together with what needs it, in one change. Packages to check or blocked, and
packages not from PyPI, are named but left out: they need a person.
"""

from __future__ import annotations

import shlex
from dataclasses import dataclass, field
from pathlib import PurePath

from django_upgrade_report import __version__
from django_upgrade_report.analysis import PackageReport, Phase, Report, Status
from django_upgrade_report.render import headline

TOOLS = ("uv", "poetry", "pdm", "pip", "pipenv")
_BY_SOURCE = {
    "uv.lock": "uv",
    "poetry.lock": "poetry",
    "pdm.lock": "pdm",
    "Pipfile.lock": "pipenv",
}


class EmitError(ValueError):
    """No tool can be told from the report's source."""


@dataclass
class Step:
    phase: str
    """``"before"``, ``"with"`` or ``"upgrade"`` (an upgrade without a phase)."""
    title: str
    commands: list[str] = field(default_factory=list)


@dataclass
class Commands:
    tool: str
    steps: list[Step]
    left_out: list[str]
    """Packages not included, with why: ``"django-taggit (blocked)"``."""


def tool_for(report: Report, wanted: str) -> str:
    """``wanted``, or for ``auto`` the tool the report's source belongs to."""
    if wanted != "auto":
        return wanted
    names = [PurePath(part.strip()).name for part in report.source.split(",")]
    for name in names:
        if name in _BY_SOURCE:
            return _BY_SOURCE[name]
    if any(n.startswith("requirements") or n.endswith((".txt", ".in")) for n in names):
        return "pip"  # with a pyproject.toml beside them, pip installs that too
    if report.source.startswith("packages installed for "):
        return "pip"
    raise EmitError(
        f"--emit auto cannot tell the tool from {report.source}: name it, one of {', '.join(TOOLS)}"
    )


def plan(report: Report, tool: str) -> Commands:
    """The steps for ``tool`` (one of :data:`TOOLS`)."""
    left_out = [
        f"{p.display_name} ({p.status.value})"
        for p in report.packages
        if p.status in (Status.BLOCKED, Status.CHECK)
    ]
    left_out += [
        f"{p.display_name} (not from PyPI)" for p in report.by_status(Status.UPGRADE) if p.source
    ]
    upgrades = [p for p in report.by_status(Status.UPGRADE) if not p.source]
    steps = []
    before = [p for p in upgrades if p.phase is Phase.BEFORE]
    if before:
        step = Step("before", "Upgrade first: one at a time, run your tests after each")
        for group in _groups(before):
            step.commands += _install(tool, group)
        steps.append(step)
    together = [p for p in upgrades if p.phase is Phase.WITH]
    if not report.health_check:
        step = Step("with", "Together with Django: one change")
        step.commands += _install(tool, together, django=(report.current_django, report.target))
        steps.append(step)
    loose = [p for p in upgrades if p.phase is None]
    if loose:
        step = Step("upgrade", "Upgrade: one at a time, run your tests after each")
        for group in _groups(loose):
            step.commands += _install(tool, group)
        steps.append(step)
    return Commands(tool, steps, left_out)


def command(report: Report, p: PackageReport, tool: str) -> str | None:
    """The command for one package on its own, ``None`` when it has none."""
    if p.status is not Status.UPGRADE or p.source or not p.target_version:
        return None
    lines = _install(tool, [p])
    return lines[0] if len(lines) == 1 else None


def render(report: Report, commands: Commands) -> str:
    lines = [f"# {headline(report)}, generated by django-upgrade-report {__version__}"]
    for number, step in enumerate(commands.steps, 1):
        lines.append(f"# {number}. {step.title}")
        lines += step.commands or ["# nothing to do"]
    if commands.left_out:
        lines.append(f"# Not included, they need a person: {', '.join(commands.left_out)}")
    return "\n".join(lines) + "\n"


def as_dict(commands: Commands) -> dict:
    return {
        "tool": commands.tool,
        "steps": [{"phase": s.phase, "commands": s.commands} for s in commands.steps],
        "left_out": commands.left_out,
    }


def _groups(packages: list[PackageReport]) -> list[list[PackageReport]]:
    """One group per package, in order, except upgrades that need each other: one group."""
    by_display = {p.display_name: p for p in packages}
    placed: set[str] = set()
    groups = []
    for p in packages:
        if p.name in placed:
            continue
        group = [p]
        for note in p.notes:
            if note.startswith("upgrade together with "):
                names = note.removeprefix("upgrade together with ").split(", ")
                group += [by_display[n] for n in names if n in by_display]
        placed.update(q.name for q in group)
        groups.append(group)
    return groups


def _install(
    tool: str, packages: list[PackageReport], django: tuple[str | None, str] | None = None
) -> list[str]:
    """The lines that move ``packages`` up together, and Django from ``django[0]`` (the
    current version, if known) to ``django[1]`` (X.Y)."""
    direct = [p for p in packages if p.direct is not False]
    transitive = [p for p in packages if p.direct is False]
    q = shlex.quote
    if tool == "pip":
        lines = [
            f"# {_pin(p.display_name, p.current)}  →  {p.display_name}=={p.target_version}"
            for p in direct
        ]
        if django:
            lines.insert(0, f"# {_pin('Django', django[0])}  →  Django~={django[1]}.0")
        lines += [
            f"# in a constraints file: {p.display_name}=={p.target_version}" for p in transitive
        ]
        return lines
    specs = [_spec(tool, p) for p in direct]
    if django:
        specs.insert(0, _django(tool, django[1]))
    lines = []
    if specs:
        add = {"uv": "uv add", "poetry": "poetry add", "pdm": "pdm add", "pipenv": "pipenv install"}
        lines.append(f"{add[tool]} {' '.join(q(s) for s in specs)}")
    for p in transitive:
        if tool == "uv":
            lines.append(f"uv lock --upgrade-package {q(f'{p.name}=={p.target_version}')}")
        else:
            update = "pipenv update" if tool == "pipenv" else f"{tool} update"
            lines.append(
                f"{update} {q(p.name)}  # comes with another package: to {p.target_version}"
            )
    return lines


def _pin(name: str, version: str | None) -> str:
    return f"{name}=={version}" if version else name


def _spec(tool: str, p: PackageReport) -> str:
    if tool == "poetry":
        return f"{p.name}@>={p.target_version}"
    return f"{p.name}>={p.target_version}"


def _django(tool: str, target: str) -> str:
    major, _, minor = target.partition(".")
    if tool == "uv":
        return f"django>={target},<{major}.{int(minor) + 1}"
    if tool == "poetry":
        return f"django@~{target}"
    return f"django~={target}.0"
